fixed header
chipsalliance/sv-tests pull request #1535
Opened 2021-05-19 19:53 UTC by Prahitha

should fix #1470 
**Note:** This issue was initially created to have the headline (title of the page) fixed as the table scrolls.

Using `scrollX: true` changes the position of the scrollbar to the end of the table instead of the window -- which I believe we do not want. So I tried using `position: fixed` for the headline but then the column headers overlap with it (could be because the header is floating?). I then added some padding to the table wrapper but there seems to be some flickering when scrolling because of this. Please correct me if I'm wrong and any suggestions on how to fix this are welcome. Thanks!

https://user-images.githubusercontent.com/44160152/118875617-e3a4ba80-b909-11eb-8bf4-4df3dca32f90.mp4

2021-05-20 12:25 UTC, mglb commented
`position: fixed` won't work here, as it pulls the element from document flow (not OK) and positions it relative to the viewport (OK on X axis, not OK on Y axis). Use `position: sticky` with fixed `left` coordinate and suitable width instead.

Note that `body` element (header's parent element) does not grow with the table (its width is equal to viewport width minus the margins), and `sticky` positioning works so that:

> The element is positioned according to the normal flow of the document, and then offset relative to its nearest scrolling ancestor **and containing block (nearest block-level ancestor)**
([source: MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/position#sticky))

You'll have to make `body` width equal to its content width with something like:
```css
width: max-content;
min-width: 100%;
box-sizing: border-box;
```

2021-05-30 16:26 UTC, Prahitha commented
This is how it looks like now, please let me know if I have to change something. Thanks!
https://user-images.githubusercontent.com/44160152/120112025-c5547f80-c191-11eb-98eb-c73a6875ea3f.mp4

2021-06-01 10:08 UTC, tgorochowik reviewed
The outcome looks good I think - I only have one question - when scrolling right, shouldn't the tool names disappear once their content is not visible? I mean - shouldn't the header for the tag name be on top (I think it is there but it does not have any text currently)

2021-06-01 11:02 UTC, Prahitha commented
yes, that's correct. I actually tried adding a classname for those 2 cells and keeping them fixed but that didn't work very well. I'll try a little more today and see how it goes.

2021-06-01 12:02 UTC, mglb requested changes
It would be nice to also "lock horizontally" the footer lines, i.e.:

```
Showing 1 to 325 of 325 entries
Download a summary in csv
Generated using sv-tests, revision: d5e09d1.
```

2021-06-01 13:10 UTC, Prahitha commented on conf/report/report.css
> +#headline {
yes, i think this can be removed

2021-06-04 15:14 UTC, Prahitha commented
- locked the lines in the footer horizontally
- the tool names now disappear when their content is not visible

2021-06-04 15:15 UTC, Prahitha commented on conf/report/report.css
> +  right: 5%;
thanks for the hint!

2021-06-11 12:49 UTC, mglb commented
FYI:  headers of invisible columns in floating header are still visible in Firefox. Not sure why.
![Screenshot_20210611_144734](https://user-images.githubusercontent.com/4888536/121688815-26e6e900-cac4-11eb-89dc-001490cb5500.png)

2021-06-11 14:38 UTC, Prahitha commented
Hmm... It seemed fine on mine though? (I only have 4 columns for now so I had to stretch them)
![Screenshot (69)](https://user-images.githubusercontent.com/44160152/121703679-b3a79c00-caf0-11eb-94c2-2b0150512e38.png)

2021-06-11 20:50 UTC, mglb commented
This one works for me too; the one that appears when you scroll down doesn't.

2021-06-12 08:17 UTC, Prahitha commented
Ah right, I only checked on Chrome and it seemed to work fine. Thanks for pointing that out!

2021-08-13 08:20 UTC, tgorochowik approved these changes
The issue in firefox is minor and in general this PR provides some visible improvements.

@Prahitha please create an issue with the description (and screenshots) of the issue with firefox

and let's merge this!

2021-08-13 08:20 UTC, merged